name: grpc
description: Dart implementation of gRPC, a high performance, open-source universal RPC framework.
version: 3.2.4

repository: https://github.com/grpc/grpc-dart

environment:
  sdk: ^3.2.0

dependencies:
  archive: ^3.4.9
  async: ^2.11.0
  crypto: ^3.0.3
  fixnum: ^1.1.0
  googleapis_auth: ^1.4.1
  meta: ^1.10.0
  http: '>=1.1.0 <2.0.0'
  http2: ^2.2.0
  protobuf: '>=3.1.0 <4.0.0'
  clock: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  lints: ">=3.0.0 <4.0.0"
  mockito: ^5.4.3
  path: ^1.8.3
  test: ^1.24.9
  stream_channel: ^2.1.2
  stream_transform: ^2.1.0
  vm_service: ^13.0.0
  fake_async: ^1.3.1

false_secrets:
 - interop/server1.key
 - test/data/localhost.key
