name: helloworld
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  async: ^2.11.0
  grpc:
    path: ../../
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
